name: Compile with BookML
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Add permissions for the workflow to push to your repo
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: cleanup old saved folder
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git rm --ignore-unmatch -rf saved
          git commit --allow-empty -m 'removing old saved folder'
          git push
     
     # this variable is set so that sections are not given separate pages
      - name: set splitlat
        run: |
          echo "SPLITAT=" >> $GITHUB_ENV
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile with bookml
        # This is your successful step that runs the Docker image as an action
        uses: docker://ghcr.io/vlmantova/bookml:latest
        with:
          # Assumes your main file is 'main.tex'. Change if necessary.
          args: -k all aux-zip # warning: aux-zip must be run *sequentially after* all

      - name: Unzip and Stage Output
        run: |
          # The output from the bookml action is a zip file
          mkdir saved
          unzip -o main.zip -d saved
          
      - name: Commit and Push HTML output
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add saved/
          git commit -m "Autogenerate HTML from bookml" || echo "No changes to commit"
          git push
