name: Compile with BookML
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Use the bookml Docker container
    container:
      image: ghcr.io/vlmantova/bookml:latest
    # Add permissions for the workflow to push to your repo
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     # this variable is set so that sections are not given separate pages
      - name: set splitlat
        run: |
          echo "SPLITAT=" >> $GITHUB_ENV
      - name: Compile with bookml
        run: |
          # The bookml user needs ownership of the files to write output
          chown -R $(id -u):$(id -g) .
          mkdir -p public-book
          # Run the bookml command
          bookml main.tex --output public-book/index.html

      - name: Commit and Push HTML output
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add public/
          git commit -m "Autogenerate HTML from bookml" || echo "No changes to commit"
          git push
