# .github/workflows/compile-latexml.yml
name: Compile LaTeX to HTML with LaTeXML

# Controls when the action will run.
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Run all steps in this job inside the official LaTeXML Docker container
    container:
       image: latexml/ar5ivist:latest

    steps:
      # 1. Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # NOTE: No installation steps for TeX Live or LaTeXML are needed!
      # They are already included in the Docker image.

      # 2. Run the LaTeXML compilation
      - name: Compile with LaTeXML
        run: |
          # Ensure the runner user owns the files to be able to write output
          chown -R $(id -u):$(id -g) .
          mkdir -p public
          latexml --dest=public/index.html main.tex

      # 3. Upload the 'public' directory as a build artifact
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: public/
