name: Save Compiled LaTeXML HTML
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: latexml/ar5ivist:latest
    # Add permissions for the workflow to push to your repo
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile with LaTeXML
        run: |
          chown -R $(id -u):$(id -g) .
          mkdir -p saved
          latexml --dest=saved/main.xml main.tex
          latexmlpost --dest=saved/index.html --format=html5 \
          --mathimages --graphicimages --pictureimages \
          --css=style.css \
          saved/main.xml

      - name: Commit and Push HTML output
        run: |
          # Configure Git user
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # Add all files in the saved directory
          git add saved/
          # Commit the changes if any exist
          git commit -m "Autogenerate HTML from LaTeXML" || echo "No changes to commit"
          # Push the changes back to the main branch
          git push
